server:
  port: 8080

spring:
  datasource:
    password: 3812
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/itransition_task4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  main:
    allow-circular-references: true